# Generated by Django 5.0.2 on 2024-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('Street_name', models.CharField(max_length=98)),
                ('estate_name', models.CharField(max_length=30)),
                ('House_number', models.CharField(max_length=10)),
                ('apartment_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='godowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('street_name', models.CharField(max_length=70)),
                ('apartment_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('hotel_name', models.CharField(max_length=70)),
                ('street_name', models.CharField(max_length=70)),
                ('apartment_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('apartment_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('apartment_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
