# Generated by Django 5.0.2 on 2024-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_estates_godowns_hotels_offices_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Town', models.CharField(max_length=124)),
                ('Bungalow_name', models.CharField(max_length=70)),
                ('eastate_name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
