# Generated by Django 5.0.2 on 2024-03-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_bungalow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungalow',
            old_name='eastate_name',
            new_name='estate_name',
        ),
    ]
