# Generated by Django 5.0.2 on 2024-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_ladieshostels'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=124)),
                ('Street', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kiosk_images/')),
            ],
        ),
    ]
